server:
  port: 8082

spring:
  application:
    name: AiService

  # ---------------------------------------------------------------------------------
  # DATABASE & MESSAGING CONFIGURATION (Must be under 'spring')
  # ---------------------------------------------------------------------------------
  data:
    mongodb:
      uri: mongodb://localhost:27017/AiRecommendations
      database: AiRecommendations

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: fitness.exchange
      default-receive-queue: activity.queue
      routing-key: activity.tracking

# ---------------------------------------------------------------------------------
# SERVICE REGISTRY AND DISCOVERY
# ---------------------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: ${GEMINI_API_KEY}